MODEL:
  BACKBONE:
    NAME: UNet3D
  DEVICE: cuda
  META_ARCHITECTURE: SemanticSegNet
  UNET:  # UNet params are defined in Abstract3DUNet
    f_maps: 16
    # final activation used during testing, if True then apply Sigmoid, else apply Softmax
    final_sigmoid: true
    in_channels: 1
    out_channels: 1