_BASE_: Base-3D-UNet.yaml
AMP_ENABLED: false
DATASET:
  CLASS_LABELS:
  - Background
  - Bladder
  - Tumor
  FOLD: 1
  PARAMS:
    crop_size:
    - 140
    - 140
    modality_roi_map:
    - PT:
      - Bladder
      - Tumor
      - Tumor2
      - Tumor3
    num_slices: 128
  TEST_DATASET_PATH:
  - data/image_dataset
  - data/test_dataset
  TRAIN_DATASET_PATH:
  - data/image_dataset
  - data/test_dataset
EARLY_STOPPING:
  MODE: min
  MONITOR: val_loss
  PATIENCE: 10
EVAL_ONLY: false
LOSS:
  FN: BCEDiceWithOverlapLoss
  PARAMS:
    bce_weight: 1.0
    class_labels:
    - Background
    - Bladder
    - Tumor
    class_weight:
    - 0
    - 1
    - 0
    class_weight_loss: both
    dice_weight: 1.0
    normalization: sigmoid
    overlap_idx:
    - 1
    - 2
    overlap_weight: 1.0
MODEL:
  BACKBONE:
    NAME: UNet3D
  DEVICE: cuda
  META_ARCHITECTURE: SemanticSegNet
  UNET:
    f_maps: 32
    final_sigmoid: true
    in_channels: 1
    out_channels: 3
NUM_WORKERS: 6
PRED_ONLY: false
RESUME: false
SOLVER:
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
  IMS_PER_BATCH: 2
  MAX_ITER: 1000
  OPTIM: Adam
  PARAMS:
    lr: 0.0005
  STEPS:
  - 300
  - 700
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 100
TEST:
  EVAL_METRICS:
  - classwise_dice_score
  - argmax_dice_score
  - overlap
  EVAL_PERIOD: 20
  FINAL_EVAL_METRICS:
  - ssim
  - hausdorff
  - classwise_dice_score
  - argmax_dice_score
  - overlap
  INFERENCE_FILE_NAME: null
  THRESHOLDS: null
  VIS_PREDS: false
TRANSFORMS:
  crop:
  - 128
  - 128
  deform_sigma: null
  div_by_max: true
  multi_scale: null
  p_flip: null
