AMP_ENABLED: true
CONFIG_FILE: seg_3d/config/mm4-nds-attend-samples-fmaps64-onlytumor-lrsched.yaml
DATASET:
  CLASS_LABELS:
  - Background
  - Bladder
  - Tumor
  - Inter
  - TURP urethra
  - R seminal
  - L seminal
  FOLD: 1
  PARAMS:
    attend_samples: true
    crop_size:
    - 196
    - 196
    modality_roi_map:
    - CT:
      - Inter
      - R seminal
      - L seminal
    - PT:
      - TURP urethra
      - Bladder
      - Tumor
      - Tumor2
      - Tumor3
    num_slices: 100
    patch_halo: null
    patch_size: null
    patch_stride: null
    patching_input_size: null
    patching_label_size: null
    slice_shape:
    - 392
    - 392
  TEST_DATASET_PATH:
  - data/image_dataset
  TEST_NUM_PATIENTS: null
  TEST_PATIENT_KEYS:
  - PSMA-01-494
  - PSMA-01-211
  - PSMA-01-518
  - PSMA-01-500
  - PSMA-01-189
  - PSMA-01-326
  - PSMA-01-596
  - PSMA-01-160
  - PSMA-01-119
  - PSMA-01-727
  TRAIN_DATASET_PATH:
  - data/image_dataset
  TRAIN_NUM_PATIENTS: null
  TRAIN_PATIENT_KEYS:
  - PSMA-01-844
  - PSMA-01-568
  - PSMA-01-486
  - PSMA-01-733
  - PSMA-01-787
  - PSMA-01-822
  - PSMA-01-658
  - PSMA-01-852
  - PSMA-01-519
  - PSMA-01-690
  - PSMA-01-360
  - PSMA-01-419
  - PSMA-01-018
  - PSMA-01-664
  - PSMA-01-105
  - PSMA-01-169
  - PSMA-01-020
  - PSMA-01-654
  - PSMA-01-770
  - PSMA-01-535
  - PSMA-01-311
  - PSMA-01-148
  - PSMA-01-485
  - PSMA-01-143
  - PSMA-01-331
  - PSMA-01-448
  - PSMA-01-045
  - PSMA-01-187
  - PSMA-01-200
  - PSMA-01-097
  - PSMA-01-732
  - PSMA-01-669
  - PSMA-01-646
  - PSMA-01-514
  - PSMA-01-676
  - PSMA-01-771
  - PSMA-01-164
  - PSMA-01-715
  - PSMA-01-110
  - PSMA-01-135
  VAL_NUM_PATIENTS: null
  VAL_PATIENT_KEYS:
  - PSMA-01-279
  - PSMA-01-634
  - PSMA-01-820
  - PSMA-01-133
  - PSMA-01-505
  - PSMA-01-835
  - PSMA-01-444
  - PSMA-01-126
  - PSMA-01-561
EARLY_STOPPING:
  MODE: min
  MONITOR: val_loss
  PATIENCE: 20
EVAL_ONLY: false
LOSS:
  FN: BCEDiceWithOverlapLoss
  PARAMS:
    bce_weight: 10.0
    class_labels:
    - Background
    - Bladder
    - Tumor
    - Inter
    - TURP urethra
    - R seminal
    - L seminal
    class_weight:
    - 1
    - 0
    - 5
    - 0
    - 0
    - 0
    - 0
    class_weight_loss: both
    dice_weight: 1.0
    normalization: sigmoid
    overlap_idx:
    - 0
    - 0
    overlap_weight: 0
MODEL:
  BACKBONE:
    NAME: UNet3D
  DEVICE: cuda
  META_ARCHITECTURE: SemanticSegNet
  UNET:
    f_maps: 64
    final_sigmoid: true
    in_channels: 2
    out_channels: 7
  WEIGHTS: ''
NUM_WORKERS: 6
OUTPUT_DIR: seg_3d/output/best_tumor_attend
PRED_ONLY: false
RESUME: false
SEED: 99
SOLVER:
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
  IMS_PER_BATCH: 1
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 1000000
  OPTIM: Adam
  PARAMS:
    lr: 0.0001
  STEPS:
  - 250
  - 500
  - 700
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
TEST:
  EVAL_METRICS:
  - classwise_dice_score
  - argmax_dice_score
  EVAL_PERIOD: 20
  FINAL_EVAL_METRICS:
  - ssim
  - hausdorff
  - classwise_dice_score
  - argmax_dice_score
  - overlap
  INFERENCE_FILE_NAME: inference.pk
  THRESHOLDS: null
  VIS_PREDS: false
TRANSFORMS:
  crop:
  - 170
  - 170
  deform_points:
  - 2
  - 2
  - 2
  deform_sigma: 5
  div_by_max: true
  multi_scale: null
  p_flip: 0.5
seed: 99
tags:
- Inter
- Bladder
- Tumor
- Inter
- TURP urethra
- R seminal
- L seminal
- CT
- PT
