_BASE_: Base-3D-UNet.yaml
AMP_ENABLED: true
DATASET:
  CLASS_LABELS:
  - Background
  - Bladder
  - Tumor
  - Inter
  # - TURP urethra
  # - R seminal
  # - L seminal
  FOLD: 1
  PARAMS:
    crop_size:
    - 196
    - 196
    modality_roi_map:
    - CT:
      - Inter
      # - R seminal
      # - L seminal
    - PT:
      - Bladder
      - Tumor
      - Tumor2
      - Tumor3
      # - TURP urethra
    num_slices: 100
    slice_shape:
    - 392
    - 392
  TEST_DATASET_PATH:
  - data/image_dataset
  TRAIN_DATASET_PATH:
  - data/image_dataset
EARLY_STOPPING:
  MODE: min
  MONITOR: val_loss
  PATIENCE: 20
EVAL_ONLY: false
LOSS:
  FN: BCEDiceWithOverlapLoss
  PARAMS:
    bce_weight: 10.0
    class_labels:
    - Background
    - Inter
    - Bladder
    - Tumor
    class_weight:
    - 1
    - 20
    - 20
    - 20
    class_weight_loss: both
    dice_weight: 1.0
    normalization: sigmoid
    overlap_idx:
    - 0
    - 0
    overlap_weight: 0
MODEL:
  BACKBONE:
    NAME: UNet3D
  DEVICE: cuda
  META_ARCHITECTURE: SemanticSegNet
  UNET:
    f_maps: 32
    final_sigmoid: true
    in_channels: 2
    out_channels: 4 # 7
  WEIGHTS: ''
NUM_WORKERS: 6
PRED_ONLY: false
RESUME: false
SOLVER:
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
  IMS_PER_BATCH: 2
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 1000000
  OPTIM: Adam
  PARAMS:
    lr: 0.0001
  STEPS:
  - 500
  - 700
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
TEST:
  EVAL_METRICS:
  - classwise_dice_score
  - argmax_dice_score
  EVAL_PERIOD: 20
  FINAL_EVAL_METRICS:
  - ssim
  - hausdorff
  - classwise_dice_score
  - argmax_dice_score
  - overlap
  INFERENCE_FILE_NAME: inference.pk
  THRESHOLDS: null
  VIS_PREDS: false
TRANSFORMS:
  crop:
  - 170
  - 170
  deform_points:
  - 2
  - 2
  - 2
  deform_sigma: 5
  div_by_max: true
  multi_scale: null
  p_flip: 0.5
# from /data/home/rodrigue/prostate-segmentation/seg_3d/output/multi-mod-3-new-data-split/1/config.yaml