AMP_ENABLED: true
DATASET:
  CLASS_LABELS:
  - Background
  - Bladder
  - Tumor
  - Inter
  - TURP urethra
  - R seminal
  - L seminal
  PARAMS:
    attend_samples: True
    crop_size:
    - 192
    - 192
    modality_roi_map:
    - CT:
      - Inter
      - R seminal
      - L seminal
    - PT:
      - TURP urethra
      - Bladder
      - Tumor
      - Tumor2
      - Tumor3
    num_slices: 128
    slice_shape:
    - 256
    - 256
  TRAIN_DATASET_PATH:
  - data/image_dataset
  - data/test_dataset
  TEST_DATASET_PATH:
  - data/image_dataset
  - data/test_dataset
  TRAIN_PATIENT_KEYS: [  # showing 'overlap, tumor sum' next to patient
      #'JGH02',
      #'JGH05',
      'PSMA-01-018',
      'PSMA-01-020',
      'PSMA-01-105',
      'PSMA-01-110',
      'PSMA-01-119',
      'PSMA-01-133',
      'PSMA-01-135',
      'PSMA-01-143',
      'PSMA-01-148',
      'PSMA-01-164',  # 58, 114
      'PSMA-01-187',
      'PSMA-01-211',
      'PSMA-01-279',
      'PSMA-01-326',  # 15, 2607
      'PSMA-01-419',
      'PSMA-01-444',
      'PSMA-01-448',
      'PSMA-01-485',
      'PSMA-01-486',
      'PSMA-01-494',
      'PSMA-01-500',
      'PSMA-01-518',  # 2, 693
      'PSMA-01-535',  # 47, 676
      'PSMA-01-561',
      'PSMA-01-568',
      'PSMA-01-596',
      'PSMA-01-634',
      'PSMA-01-654',
      'PSMA-01-669',
      'PSMA-01-715',
      'PSMA-01-727',
      'PSMA-01-732',
      'PSMA-01-733',
      'PSMA-01-770',
      'PSMA-01-771',
      'PSMA-01-820',  # 4, 1309
      'PSMA-01-835',
      'PSMA-01-852'
  ]
  VAL_PATIENT_KEYS: [
      #'JGH03',
      'PSMA-01-505',  # 59, 256
      'PSMA-01-646',  # 6, 1059
      'PSMA-01-664',
      'PSMA-01-676'  # 4, 84
  ]
  TEST_PATIENT_KEYS: [
      #'JGH01',
      #'JGH04',
      'PSMA-01-045',
      'PSMA-01-097',
      'PSMA-01-126',  # 144, 647
      'PSMA-01-160',
      'PSMA-01-169',
      'PSMA-01-189',  # 1, 256
      'PSMA-01-200',
      'PSMA-01-311',
      'PSMA-01-331',  # 3, 458
      'PSMA-01-360',
      'PSMA-01-514',
      'PSMA-01-519',
      'PSMA-01-658',
      'PSMA-01-690',  # 33, 1089
      'PSMA-01-787',
      'PSMA-01-822',
      'PSMA-01-844'
  ]
EARLY_STOPPING:
  MODE: min
  MONITOR: val_loss
  PATIENCE: 10
EVAL_ONLY: false
LOSS:
  FN: BCEDiceLoss
  PARAMS:
    dice_weight: 1.
    bce_weight: 1.
    normalization: sigmoid
    class_balanced: True
MODEL:
  BACKBONE:
    NAME: UNet3D
  DEVICE: cuda
  META_ARCHITECTURE: SemanticSegNet
  UNET:
    f_maps: 16
    final_sigmoid: true
    in_channels: 2
    out_channels: 7
  WEIGHTS: ''
RESUME: false
SEED: 99
SOLVER:
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
  IMS_PER_BATCH: 1
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 1000000
  OPTIM: Adam
  PARAMS:
    lr: 0.0001
  STEPS:
  - 240
  - 480
  - 700
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
TEST:
  EVAL_METRICS:
  - classwise_dice_score
  - argmax_dice_score
  - overlap
  EVAL_PERIOD: 20
  INFERENCE_FILE_NAME: inference.pk
  THRESHOLDS: null
TRANSFORMS:
  crop: null
  div_by_max: true
  p_flip: null
# TODO: transforms?