_BASE_: Base-3D-UNet.yaml
MODEL:
  UNET:
    in_channels: 2
    out_channels: 7
LOSS:
  FN: BCEDiceLoss
  PARAMS:
    bce_weight: 1.
    dice_weight: 1.
    normalization: sigmoid
DATASET:
  TRAIN_DATASET_PATH:
  - data/image_dataset
  TEST_DATASET_PATH:
  - data/image_dataset
  TRAIN_NUM_PATIENTS: 40
  VAL_NUM_PATIENTS: 19
  CLASS_LABELS:
    - Background
    - Prostate
    - Bladder
    - Tumor
    - TURP urethra
    - R seminal
    - L seminal
  PARAMS:
    modality:
    - CT
    - PT
    rois:
    - Inter
    - Bladder
    - Tumor
    - Tumor2
    - Tumor3
    - TURP urethra
    - R seminal
    - L seminal
    slice_shape: (200, 200)
    crop_size: (128, 128)
    num_slices: 100
