_BASE_: Base-3D-UNet.yaml
UNSUPERVISED: True
MODEL:
  UNET:
    in_channels: 2
    out_channels: 7
LOSS:
  FN: BCEDiceMSLoss
  PARAMS:
    bce_weight: 1.
    dice_weight: 1.
    normalization: sigmoid
DATASET:
  TRAIN_DATASET_PATH:
  - data/image_dataset
  TEST_DATASET_PATH:
  - data/image_dataset
  TRAIN_NUM_PATIENTS: 40
  VAL_NUM_PATIENTS: 19
  CLASS_LABELS:
    - Background
    - Inter  # this is the prostate
    - Bladder
    - Tumor
    - TURP urethra
    - R seminal
    - L seminal
  PARAMS:
    modality_roi_map:
      - CT:
        - Inter
        - R seminal
        - L seminal
      # - Bladder
      - PT:
        - TURP urethra
        - Bladder  # we ensure there is no overlap between gt bladder and tumor so they both need to come from PT
        - Tumor
        - Tumor2
        - Tumor3
    slice_shape: (200, 200)
    crop_size: (128, 128)
    num_slices: 100
