_BASE_: Base-3D-UNet.yaml
MODEL:
  UNET:
    out_channels: 2
LOSS:
  FN: WBCEDiceLoss
  PARAMS:
    bce_weight: 1.
    dice_weight: 1.
    normalization: sigmoid
DATASET:
  TRAIN_DATASET_PATH:
  - /home/rodrigue/prostate-segmentation/data/image_dataset
  TEST_DATASET_PATH:
  - /home/rodrigue/prostate-segmentation/data/image_dataset
  TRAIN_NUM_PATIENTS: 40
  VAL_NUM_PATIENTS: 19
  CLASS_LABELS:
    - Background
    - Prostate
  PARAMS:
    modality: CT
    rois:
    - Inter
    crop_size:
      - 200
      - 200
    num_slices: 100
