_BASE_: Base-3D-UNet.yaml
TEST:
  EVAL_METRICS:
  - classwise_dice_score
  - argmax_dice_score
MODEL:
  UNET:
    f_maps: 16
    out_channels: 2
LOSS:
  FN: BCEDiceWithOverlapLoss
  PARAMS:
    bce_weight: 1.
    dice_weight: 1.
    overlap_weight: 0
    overlap_idx: null  # tuple containing channel indices of pred, gt for overlap computation
    #                      # (pred bladder channel, gt tumor channel)
    class_weight: [0, 1]  # set weight for background to 0
    class_weight_loss: both
    normalization: sigmoid
EARLY_STOPPING:
  MODE: max
  MONITOR: classwise_dice_score/Inter
  PATIENCE: 10
DATASET:
  TRAIN_DATASET_PATH:
  - data/image_dataset
  - data/test_dataset
  TEST_DATASET_PATH:
  - data/image_dataset
  - data/test_dataset
  CLASS_LABELS:
    - Background
    - Inter
  PARAMS:
    modality_roi_map:
      - CT:
        - Inter
    crop_size:
      - 200
      - 200
    num_slices: 100
    # old splits
  TRAIN_PATIENT_KEYS: [  # showing 'overlap, tumor sum, overlap / tumor sum * 100' next to patient
      'PSMA-01-018',
      'PSMA-01-020',
      'PSMA-01-105',
      'PSMA-01-110',
      'PSMA-01-119',
      'PSMA-01-133',
      'PSMA-01-135',
      'PSMA-01-143',
      'PSMA-01-148',
      'PSMA-01-164',  # 58, 114, 50%
      'PSMA-01-187',
      'PSMA-01-211',
      'PSMA-01-279',
      'PSMA-01-326',  # 15, 2607, 0.6%
      'PSMA-01-419',
      'PSMA-01-444',
      'PSMA-01-448',
      'PSMA-01-485',
      'PSMA-01-486',
      'PSMA-01-494',
      'PSMA-01-500',
      'PSMA-01-518',  # 2, 693, 0.2%
      'PSMA-01-535',  # 47, 676, 7%
      'PSMA-01-561',
      'PSMA-01-568',
      'PSMA-01-596',
      'PSMA-01-634',
      'PSMA-01-654',
      'PSMA-01-669',
      'PSMA-01-715',
      'PSMA-01-727',
      'PSMA-01-732',
      'PSMA-01-733',
      'PSMA-01-770',
      'PSMA-01-771',
      'PSMA-01-820',  # 4, 1309, 0.3%
      'PSMA-01-835',
      'PSMA-01-852'
  ]
  VAL_PATIENT_KEYS: [
      'PSMA-01-646',  # 6, 1059, 0.6%
      'PSMA-01-664',
      'PSMA-01-676'  # 4, 84, 5%
  ]
  TEST_PATIENT_KEYS: [
      # 'JGH01',
      # 'JGH02',
      # 'JGH03',
      # 'JGH04',
      # 'JGH05',
      'PSMA-01-505',  # 59, 256, 23%
      'PSMA-01-045',
      'PSMA-01-097',
      'PSMA-01-126',  # 144, 647, 22%
      'PSMA-01-160',
      'PSMA-01-169',
      'PSMA-01-189',  # 1, 256, 0.4%
      'PSMA-01-200',
      'PSMA-01-311',
      'PSMA-01-331',  # 3, 458, 0.7%
      'PSMA-01-360',
      'PSMA-01-514',
      'PSMA-01-519',
      'PSMA-01-658',
      'PSMA-01-690',  # 33, 1089, 3%
      'PSMA-01-787',
      'PSMA-01-822',
      'PSMA-01-844'
  ]
SOLVER:
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
  IMS_PER_BATCH: 2
  MAX_ITER: 1000000
  OPTIM: Adam
  PARAMS:
    lr: 0.0001
  STEPS:
  - 240
  - 480
  - 700
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
  # start with no transforms