### Config for training a prostate segmentation model from PET/CT images.

AMP_ENABLED: true
DATASET:
  CLASS_LABELS:
  - Background
  - Inter
  - Bladder
  - Tumor
  # - TURP urethra
  # - R seminal
  # - L seminal
  FOLD: 1
  PARAMS:
    crop_size:
    - 170
    - 170
    modality_roi_map:
    - CT:
      - Inter  # prostate annotated using the INTERpolation tool (MIM)
      # - R seminal
      # - L seminal
    - PT:
      - Bladder
      - Tumor
      - Tumor2
      - Tumor3
      # - TURP urethra
    num_slices: 100
    slice_shape:  # upscales PET to this shape
    - 512
    - 512
EARLY_STOPPING:
  MODE: max
  MONITOR: classwise_dice_score/Inter
  PATIENCE: 10
EVAL_ONLY: false
LOSS:
  FN: BCEDiceLoss
  PARAMS:
    bce_weight: 1.0
    class_labels:
    - Background
    - Inter
    - Bladder
    - Tumor
    # - TURP urethra
    # - R seminal
    # - L seminal
    class_weight:
    - 0.01
    - 0.89
    - 0.1
    - 0
    dice_weight: 1.0
    normalization: sigmoid
MODEL:
  BACKBONE:
    NAME: UNet3D
  DEVICE: cuda
  META_ARCHITECTURE: SemanticSegNet
  UNET:
    f_maps: 32
    final_sigmoid: true
    in_channels: 2   # 2 input channels: PET, CT
    out_channels: 4  # 4 classes
NUM_WORKERS: 6
PRED_ONLY: false
RESUME: false
SEED: 99
SOLVER:
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.1
  IMS_PER_BATCH: 2
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 1000000
  OPTIM: Adam
  PARAMS:
    lr: 0.0001
  STEPS: []
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 0
  WARMUP_METHOD: linear
TEST:
  EVAL_METRICS:
  - classwise_dice_score
  - argmax_dice_score
  EVAL_PERIOD: 20
  FINAL_EVAL_METRICS:
  - ssim
  - hausdorff
  - classwise_dice_score
  INFERENCE_FILE_NAME: inference.pk
  THRESHOLDS:
  - null
  - 0.5
  - 0.5
  - 1  # zero out tumor
  VIS_PREDS: true
TRANSFORMS:
  crop_size: null
  deform_points: null
  deform_sigma: null
  min_max_norm: true
  ignore_bg: false
  multi_scale: null
  p_flip: null
seed: 99